# typings/fitz/__init__.pyi
from typing import Iterator

class Page:
    def get_text(self, option: str = ...) -> str: ...
    def get_pixmap(self, matrix: object = ..., alpha: bool = ...) -> object: ...
    def insert_text(self, point: object, text: str) -> None: ...
    def get_images(self) -> list[tuple]: ...
    def search_for(self, string: str) -> list[object]: ...

class Document:
    def __enter__(self) -> Document: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Page: ...
    def __iter__(self) -> Iterator[Page]: ...
    def close(self) -> None: ...

def open(filepath: str) -> Document: ...
